spring:
  datasource:
    url: jdbc:mysql://47.97.72.245:3306/foodie-dev?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
